name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1c38e49a035603d55a7895f7b686c901f013dd1f5cb6361ab758ee97c2982e1"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.64"
