name = "Mc"
author = "ana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d0adf880c2c6bcc3d1349a8d2547d569ec105a5758e90ea21acaddd5a19f5bf"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.64"
